spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: secret
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      accept-float-as-int: false